# 데이터분석 스터디 01

* numpy : array 단위로 데이터 관리, 연산 수행
* pandas : 행렬 관리, 데이터 처리
* matplot : 시각화

## numpy

In [4]:
# numpy 호출, np로 부른다고 약속
import numpy as np

In [5]:
list1 = [1,2,3,4,5]

In [6]:
#numpy 이용하여 array 정의
n1 = np.array(list1)
n1

array([1, 2, 3, 4, 5])

In [8]:
print(n1.shape)    # array 크기 확인
print(type(list1))
print(type(n1))

(5,)
<class 'list'>
<class 'numpy.ndarray'>


In [10]:
#바로 array 생성
n2 = np.array([11,12,13,14,15,16])
print(n2)
print(type(n2))

[11 12 13 14 15 16]
<class 'numpy.ndarray'>


In [11]:
#데이터 타입 확인
n2.dtype

dtype('int32')

In [26]:
n2[2]

13

In [12]:
data1 = [[1,2,3],[4,5,6],[7,8,9]]
print(data1)
print(type(data1))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>


In [15]:
m1 = np.array(data1)
print(m1)
print(type(m1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [27]:
m1[2]

array([7, 8, 9])

In [28]:
m1[1][1]

5

In [16]:
m1.mean()

5.0

### np.zeros(), np.ones(), np.arange() 함수

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
np3 = np.zeros((3,1))
print(np3)
print(type(np3))

[[0.]
 [0.]
 [0.]]
<class 'numpy.ndarray'>


In [23]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [25]:
np.arange(4,9)

array([4, 5, 6, 7, 8])

## pandas

In [29]:
import pandas as pd

* Series와 Data Frame의 자료구조 존재

### Series

In [30]:
s1 = pd.Series([1,7, 5, 3])
print(s1)
print(type(s1))

0    1
1    7
2    5
3    3
dtype: int64
<class 'pandas.core.series.Series'>


In [31]:
#값만 출력
s1.values

array([1, 7, 5, 3], dtype=int64)

In [32]:
#인덱스만 확인
s1.index

RangeIndex(start=0, stop=4, step=1)

* 인덱스 변경 가능

In [33]:
s2 = pd.Series([1,7,5,3], index = ['a','d','c','b'])
print(s2)
print(type(s2))

a    1
d    7
c    5
b    3
dtype: int64
<class 'pandas.core.series.Series'>


* dictionary 형태 Series로 생성 가능 (key -> index)

In [34]:
dic1 = {'jiwoo' : 23, 'yeonsoo' : 20, 'inseo' : 18}
dics1 = pd.Series(dic1)
print(type(dic1))
print(dics1)
print(type(dics1))

<class 'dict'>
jiwoo      23
yeonsoo    20
inseo      18
dtype: int64
<class 'pandas.core.series.Series'>


In [35]:
dics1.name = 'family'
dics1.index.name = 'name'
print(dics1)

name
jiwoo      23
yeonsoo    20
inseo      18
Name: family, dtype: int64


** dictionary형태의 Series도 인덱스 변경 가능

In [37]:
dics1.index = ['first', 'second','third']
print(dics1)

first     23
second    20
third     18
Name: family, dtype: int64


### Data Frame

In [41]:
data1 = {'name' : ['jiwoo', 'yeonsoo', 'inseo'],
        'year' : [1998, 2001, 2003],
        'age' : [23, 20, 18],
        'mbti' : ['ISTJ', 'ENFP', 'INFP']}
df1 = pd.DataFrame(data1)
df1

name  year  age  mbti
0    jiwoo  1998   23  ISTJ
1  yeonsoo  2001   20  ENFP
2    inseo  2003   18  INFP

In [44]:
print(df1.index) #행 방향 인덱스
print(df1.columns) #열 방향의 인덱스
print(df1.values) #값 출력

RangeIndex(start=0, stop=3, step=1)
Index(['name', 'year', 'age', 'mbti'], dtype='object')
[['jiwoo' 1998 23 'ISTJ']
 ['yeonsoo' 2001 20 'ENFP']
 ['inseo' 2003 18 'INFP']]


In [47]:
# 열 인덱스 순서 바꾸어 작성해도 맞추어 기록됨. 없는 값은 NaN
df2 = pd.DataFrame(data1, columns = ['name', 'age', 'mbti', 'year', 'hobby'], 
                   index = ['first', 'second', 'third'])
df2

name  age  mbti  year hobby
first     jiwoo   23  ISTJ  1998   NaN
second  yeonsoo   20  ENFP  2001   NaN
third     inseo   18  INFP  2003   NaN

In [48]:
# 데이터프레임 부분 출력 가능
df2['name']

first       jiwoo
second    yeonsoo
third       inseo
Name: name, dtype: object

In [49]:
df2[['name','age']]

name  age
first     jiwoo   23
second  yeonsoo   20
third     inseo   18

In [51]:
df2['hobby'] = np.arange(3) # 값 배정 가능
df2

name  age  mbti  year  hobby
first     jiwoo   23  ISTJ  1998      0
second  yeonsoo   20  ENFP  2001      1
third     inseo   18  INFP  2003      2

In [53]:
#Series 추가 가능
main = pd.Series(['CS','English'], index = ['first', 'second'])
df2['main'] = main
df2

name  age  mbti  year  hobby     main
first     jiwoo   23  ISTJ  1998      0       CS
second  yeonsoo   20  ENFP  2001      1  English
third     inseo   18  INFP  2003      2      NaN

In [54]:
del df2['hobby'] #열 삭제 가능
df2

name  age  mbti  year     main
first     jiwoo   23  ISTJ  1998       CS
second  yeonsoo   20  ENFP  2001  English
third     inseo   18  INFP  2003      NaN

#### 행 인덱싱

In [55]:
df2 [0:1]

name  age  mbti  year main
first  jiwoo   23  ISTJ  1998   CS

In [57]:
#가능하지만 비추
df2['second' : 'third']

name  age  mbti  year     main
second  yeonsoo   20  ENFP  2001  English
third     inseo   18  INFP  2003      NaN

In [58]:
#보통 .loc함수 사용
df2.loc['second']

name    yeonsoo
age          20
mbti       ENFP
year       2001
main    English
Name: second, dtype: object

In [61]:
df2.loc['second':'third']

name  age  mbti  year     main
second  yeonsoo   20  ENFP  2001  English
third     inseo   18  INFP  2003      NaN

In [62]:
df2.loc[:, 'name'] #df2['name']과 동일

first       jiwoo
second    yeonsoo
third       inseo
Name: name, dtype: object

In [65]:
#새로운 행 삽입
df2.loc['mom', :] = ['jieun', 50, 'ENFP', 1970, 'piano']
df2

name   age  mbti    year     main
first     jiwoo  23.0  ISTJ  1998.0       CS
second  yeonsoo  20.0  ENFP  2001.0  English
third     inseo  18.0  INFP  2003.0      NaN
mom       jieun  50.0  ENFP  1970.0    piano

In [66]:
#인덱스 번호 사용 .iloc
df2.iloc[2]

name    inseo
age        18
mbti     INFP
year     2003
main      NaN
Name: third, dtype: object

In [67]:
df2.iloc[2:]

name   age  mbti    year   main
third  inseo  18.0  INFP  2003.0    NaN
mom    jieun  50.0  ENFP  1970.0  piano

In [69]:
df2.iloc[:,0:2]

name   age
first     jiwoo  23.0
second  yeonsoo  20.0
third     inseo  18.0
mom       jieun  50.0